### ISSUE TITLE
Sign_key

### ISSUE THREAD

**Issue by dink3r1337** [Numenorean/DurakOnlineBot#2]
Как получить ключ подписи запроса?

**Comment by Numenorean** [comment]
Отдебажить приложение, какую игру нужно?

**Comment by dink3r1337** [comment]
Шашки онлайн

**Comment by Numenorean** [comment]
> Шашки онлайн

falgcanfxehkufvcukydbvkudvgkuydsdasfdfvwvcyksed - алгоритм тот же
