### ISSUE TITLE
Как отмыть кредиты?

### ISSUE THREAD

**Issue by Zeo-star** [Numenorean/DurakOnlineBot#20]
как вывести кредиты чтобы их не обнулили?

**Comment by zerosar** [comment]
Присоединяйтесь к вопросу. Свои 7к ботом довел до 30к с мелочью. После этого удалил ботов с друзей и сыграл пару раз. В итоге обнуление при заходе в игру через пару часов.

**Comment by Zeo-star** [comment]
точно такая же проблема

**Comment by zerosar** [comment]
Есть конечно вариант переделать бота чтобы он:
1. Создавал игру на нескольких игроков
2. Приглашал цель накрутки.
3. Снимал пароль с игровой сессии от аккаунта бота и аккаунта цели.
4. Ждал готовности всех игроков.
5. Ну а дальше слив.
 Ноо автор бота или кто-то другой должен все это реализовать и не факт что получится избежать обнуления!!

**Comment by deltabravozulu** [comment]
Yeah I need to figure this out too. Lost about a million after transferring it around.
