### ISSUE TITLE
Хелп

### ISSUE THREAD

**Issue by OctaneAL** [Numenorean/DurakOnlineBot#21]
Не совсем понимаю где взять RUCAPTCHA_KEY

**Comment by zerosar** [comment]
Он не нужен. 
Пример:
SIGN_KEY = 'oc3q7ingf978mx457fgk4587fg847'
RUCAPTCHA_KEY = ''
NAME = 'Primer'
USER_ID = 39339354
TOKEN = '$2a$07$s.4Vcf/3WOEcKuDmziF/Zu'
HUMAN_CAPTCHA_SOLVE = True
level = 'INFO'

**Comment by zerosar** [comment]
Но!!! за накрутку меня обнулили через пару часов. Накрутил с 7к до 30к. Лучше создавать тестовые аккаунты на телефоне для проверки бота. С основного не рекомендую!!

**Comment by OctaneAL** [comment]
Я собирался на левом аккаунте тестить бота, а потом, в случае успеха, перекидывать все на основу. Так же должно сработать? Даже если обнулят, будет уроком ;d
Спасибо, попробую
