### ISSUE TITLE
Ничего не происходит

### ISSUE THREAD

**Issue by OctaneAL** [Numenorean/DurakOnlineBot#22]
Вроде ввел все данные правильно, бот добавился в друзья, но дальше ничего не происходит
![ab](https://user-images.githubusercontent.com/97474275/148923243-14a9e9e5-5a68-4ade-9eb4-dfb497ff4fda.PNG)

**Comment by OctaneAL** [comment]
Возможно проблема в user_id (мб я его не так нашел), я его брал в http canary со строки authorized {"id" : "циферки"}

**Comment by zerosar** [comment]
Пример конфига, только с рандомными данными:

SIGN_KEY = 'oc3q7ingf978mx457fgk4587fg847'
RUCAPTCHA_KEY = ''
NAME = 'Primer'
USER_ID = 39339354
TOKEN = '$2a$07$s.4Vcf/3WOEcKuDmziF/Zu'
HUMAN_CAPTCHA_SOLVE = True
level = 'INFO'

**Comment by zerosar** [comment]
+ игра на телефоне / эмуляторе должна быть закрыта так как бот берет управление вашим аккаунтом на себя

**Comment by zerosar** [comment]
И ещё: на данный момент высокий риск бана. Поэтому не используйте основной аккаунт от игры. Зарегистрируйте акк тестовый, для бота.

**Comment by OctaneAL** [comment]
Попробовал запустить бота с закрытой игрой, все равно ничего не происходит. Зашел в игру через минут 5 после появления строки "Sent friend request", запрос в друзья просто висит.

**Comment by Zeo-star** [comment]
> Игра на телефоне / эмуляторе должна быть закрыта так как бот берет управление вашим аккаунтом на себя.

не обязательно

**Comment by OctaneAL** [comment]
Попробовал еще раз скопировать и вставить token и user id, вроде заработало o_0

**Comment by magaiiooo** [comment]
проверил уже несколько раз юзер айди и токен. просто висит на запросе в друзьях. версия питона же 3.9 должна?
