### ISSUE TITLE
Не начинается матч

### ISSUE THREAD

**Issue by Zundonza** [Numenorean/DurakOnlineBot#23]
В конфиге всё написал, запустил бота, connected, session verifed, auth is succesful, session verifed, account is ready, auth is succesful,
sent friend request, дальше ничего не происходит. Запустил в debug, после отправления заявки в друзья, сервер отвечает пустыми ответами. Скрин прикреплю.
Скрин: [https://imgur.com/a/QDGu1l0](url)

**Comment by Zundonza** [comment]
В друзья стал добавляться, я принимаю, дальше ничего не происходит...

**Comment by Zundonza** [comment]
В друзья добавился, игра создаётся, все готовы, но игра не начинается, щас продебажу, может выясню

**Comment by Zundonza** [comment]
err("code":"not enough points") как решить?

**Comment by Numenorean** [comment]
Чтобы начать накрутку у тебя должно быть 2500 на основном аккаунте

**Comment by Zundonza** [comment]
> Чтобы начать накрутку у тебя должно быть 2500 на основном аккаунте

Всё заработало, спасибо.
