### ISSUE TITLE
Проблема с модулем Pillow

### ISSUE THREAD

**Issue by DaRkNiGhT05-fire** [Numenorean/DurakOnlineBot#30]
Ошибка в скрине, также встрял matplotlib
![Screenshot_2022-02-08-21-39-43-986_com termux](https://user-images.githubusercontent.com/80477727/153054086-40780164-2f81-4a4b-b778-fd2990236715.jpg)

**Comment by Numenorean** [comment]
не уверен что pillow из под termux можно использовать, можешь использовать рукапчу

**Comment by DaRkNiGhT05-fire** [comment]
Я использовал до этого вашего бота и все было хорошо, после 2-3 месяцев я установил снова термукс и выскочила такая ошибка

**Comment by DaRkNiGhT05-fire** [comment]
> не уверен что pillow из под termux можно использовать, можешь использовать рукапчу

Все проблема была решена, я удалил matplotlib и pillow из кода в api.py
